// Bundles the custom server (src/server/index.ts and everything it imports from src/) into a
// single plain-JavaScript file so production runs on `node` directly, without tsx.
//
// Why: in production the server used to be started with `npx tsx src/server/index.ts`. tsx keeps an
// ESM loader worker thread alive for on-the-fly TypeScript transforms; on the VPS (Node 20) that
// thread pinned a full CPU core even with zero WhatsApp sessions. A pre-built bundle has no
// transform layer at all: `node dist/server/index.js` is just the app.
//
// node_modules stay external, so Next.js, Baileys, Prisma, etc. are loaded from node_modules exactly
// as before; only our own source is compiled. The one exception is `next-auth` / `@auth/core`: they
// ship ESM that imports "next/server" without an extension, which Node's native ESM resolver rejects
// (tsx used to paper over that) — so those two are bundled in, and their imports of `next/*` become
// ordinary require() calls that resolve fine.
// CommonJS output is used on purpose: it keeps `./runtime-polyfills` running before `next-auth` is
// loaded (ESM output would hoist the external imports above it and bring back the AsyncLocalStorage
// crash).
import { build } from "esbuild";
import { rmSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const outfile = resolve(root, "dist/server/index.js");

rmSync(resolve(root, "dist/server"), { recursive: true, force: true });

// Packages that are compiled into the bundle instead of being require()d from node_modules.
const BUNDLED_PACKAGES = /^(next-auth|@auth\/core)(\/|$)/;

/** Every bare import (a package or a node builtin) stays external, except BUNDLED_PACKAGES. */
const externalizeNodeModules = {
    name: "externalize-node-modules",
    setup(b) {
        b.onResolve({ filter: /^[^./]/ }, args => {
            if (args.path.startsWith("@/")) return undefined; // tsconfig path alias → our own source
            if (BUNDLED_PACKAGES.test(args.path)) return undefined;
            return { path: args.path, external: true };
        });
    }
};

const started = Date.now();
const result = await build({
    absWorkingDir: root,
    entryPoints: [resolve(root, "src/server/index.ts")],
    outfile,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node20",
    alias: { "@": resolve(root, "src") },
    plugins: [externalizeNodeModules],
    tsconfig: resolve(root, "tsconfig.json"),
    sourcemap: true,
    sourcesContent: false,
    legalComments: "none",
    logLevel: "warning",
    banner: { js: `/* ${pkg.name} v${pkg.version} server bundle — generated by scripts/build-server.mjs, do not edit */` },
    metafile: true
});

const inputs = Object.keys(result.metafile.inputs).length;
const bytes = result.metafile.outputs[Object.keys(result.metafile.outputs).find(k => k.endsWith(".js"))]?.bytes ?? 0;
console.log(`✓ server bundle: dist/server/index.js (${(bytes / 1024).toFixed(0)} kB, ${inputs} source files, ${Date.now() - started} ms)`);
